export { default as PDictSelect } from './pdictSelect.vue'
export { default as PModal } from './pmodal.vue'
export { default as BrandSelect } from './brandSelect.vue'
export { default as TableView } from './tableView.vue'
export { default as PCard } from './pcard.vue'
export { default as IngredientSelection } from './ingredientSelection.vue'
